INSERT OR IGNORE INTO tickets VALUES
('SD-1042','Cannot complete login after replacing my phone','Amira Solis','Harbor & Finch','2026-05-20T09:14:00Z','New','Medium','Login / MFA','Hello SecureDesk team, I changed phones yesterday and my authenticator codes no longer work. I still know my password but cannot reach the dashboard. Can someone help me get access again?'),
('SD-1047','Question about an extra seat on our invoice','Theo Nordin','Northstar Studio','2026-05-20T11:32:00Z','New','Low','Billing','Our May invoice appears to include 21 seats, but our team list shows 20 active people. Could you explain how seats are counted before we renew?'),
('SD-1051','Browser extension button is missing after Chrome update','Maya Chen','Brightpath Learning','2026-05-21T08:06:00Z','New','Medium','Browser Extension','Chrome updated this morning and the SecureDesk button disappeared from my toolbar. I use it to report messages during training. The extension still seems listed in Chrome but I cannot launch it.'),
('SD-1055','Notification email arrived nearly an hour late','Louis Patel','Juniper Works','2026-05-21T15:44:00Z','New','Medium','Email Notifications','A security training reminder created at 14:05 only reached several colleagues at 14:58. Are notifications delayed? We have not changed our mail rules recently.'),
('SD-1059','Team lead cannot view campaign reports','Ines Duarte','Orbit Legal','2026-05-22T10:18:00Z','New','Medium','Permissions','I granted Rowan the Team Lead role, but Reports remains unavailable in the navigation. Other team leads see it normally. We need report access for this week''s review.'),
('SD-1063','API requests now return 401 authentication error','Daniel Okoro','Copperline Systems','2026-05-22T13:57:00Z','New','High','API Authentication','Our nightly user sync started failing with HTTP 401 at 02:00 UTC. We authenticate using a service token. We rotated a secret last week but it worked until today.'),
('SD-1068','Multiple employees received a suspicious training email link','Sara Voss','Granite Health Labs','2026-05-23T07:21:00Z','New','High','Security / Phishing Report','Several employees received an email that looks like SecureDesk training, but the sign-in button points to a domain we do not recognize. Two people clicked before reporting it. Please investigate urgently.'),
('SD-1074','Directory sync has stopped importing new employees','Hassan Reid','Maple Peak Finance','2026-05-23T12:40:00Z','New','High','Integration Sync','Our directory integration completed with warnings overnight, and five new starters are missing in SecureDesk. Existing employees are present. The last successful full sync was two days ago.');

INSERT OR IGNORE INTO knowledge_articles VALUES
('KB-001','Recover Access After Replacing an MFA Device','Login / MFA','Users who still know their password can regain access using saved recovery codes or an administrator-verified MFA reset.','["Check for a saved SecureDesk recovery code.","Ask an organization administrator to begin the identity-verified MFA reset flow.","Re-enroll a new authenticator after access is restored."]','Escalate if identity verification succeeds but re-enrollment fails or access remains blocked.','2026-04-18','["login","mfa","authenticator","phone","code","access"]'),
('KB-002','MFA Code Time Synchronization Checks','Login / MFA','Authenticator codes may fail when a device clock is not set to automatic time synchronization.','["Confirm automatic date and time are enabled on the authenticator device.","Try a newly generated code after time synchronization."]','Escalate if multiple enrolled users experience code failures simultaneously.','2026-03-02','["mfa","authenticator","code","time","login"]'),
('KB-003','How Active Seats Appear on an Invoice','Billing','SecureDesk invoices count active billable seats at the billing snapshot time; removed users can appear if removed after that snapshot.','["Compare the invoice period with the user activity export.","Confirm whether a seat was removed after the billing snapshot."]','Request billing review when the export and invoice snapshot do not reconcile.','2026-04-25','["billing","invoice","seat","renew","active"]'),
('KB-004','Re-enable the SecureDesk Browser Extension After an Update','Browser Extension','Chrome updates can unpin an enabled extension from the toolbar without removing it.','["Open Chrome Extensions and confirm SecureDesk is enabled.","Select the Extensions menu in the toolbar and pin SecureDesk.","Reload the current browser tab before testing the button."]','Escalate if the extension is enabled but cannot be opened, or an extension error is shown.','2026-05-11','["browser","extension","chrome","button","toolbar","missing","update"]'),
('KB-005','Collect Browser Extension Diagnostics','Browser Extension','Support can request the browser version and extension version when toolbar recovery does not solve an extension issue.','["Record the Chrome version.","Record the SecureDesk extension version from the extensions page.","Capture the exact displayed error, if any."]','Provide diagnostics to engineering for reproducible launch failures.','2026-04-28','["chrome","extension","version","error","diagnostic"]'),
('KB-006','Delayed Notification Email Checklist','Email Notifications','Notification delivery delays can be investigated using message timestamps and recipient mail filtering information.','["Collect the notification creation time and received time including timezone.","Ask whether all recipients or only some recipients were affected.","Check whether recipient mail systems quarantined or deferred the message."]','Escalate repeated delays over 30 minutes across multiple recipients with timestamp evidence.','2026-05-04','["email","notification","delayed","late","mail","recipient"]'),
('KB-007','Report Visibility and Team Lead Permissions','Permissions','Report access requires a Team Lead role assignment scoped to at least one active team.','["Confirm the user is assigned Team Lead.","Confirm at least one active team is selected in the role scope.","Ask the user to sign out and sign in again after a role change."]','Escalate when an active scope is present and report navigation remains missing after a new session.','2026-04-30','["permission","team","lead","report","role","navigation"]'),
('KB-008','Service Token Authentication for the SecureDesk API','API Authentication','API requests must provide an active service token as a Bearer token and target its authorized environment.','["Confirm the Authorization header uses Bearer followed by the active token.","Confirm the token has not expired or been revoked.","Confirm the API base URL matches the token environment."]','Escalate if an active correctly scoped token returns 401 with a request ID and timestamp.','2026-05-07','["api","authentication","401","token","secret","bearer"]'),
('KB-009','Rotating API Credentials Without Sync Downtime','API Authentication','During token rotation, the integration must be updated to use the newly active token before the previous token is revoked.','["Verify which token identifier the integration currently uses.","Run one authenticated health request with the new token."]','Escalate unexpected rejection of a verified active token.','2026-03-20','["api","token","rotation","secret","sync","401"]'),
('KB-010','Report a Suspected SecureDesk Impersonation Email','Security / Phishing Report','Messages imitating SecureDesk with unrecognized links should be treated as suspected phishing and preserved for investigation.','["Do not click additional links or enter credentials.","Preserve the original message and headers.","Record affected recipients and whether anyone clicked or submitted information.","Follow the organization''s internal incident-response process."]','Escalate immediately when users clicked a suspected impersonation link or credentials may have been exposed.','2026-05-15','["phishing","suspicious","email","link","clicked","security","domain"]'),
('KB-011','Directory Integration Sync Warning Triage','Integration Sync','A sync warning may prevent newly added directory members from appearing while existing records remain available.','["Record the last successful sync timestamp.","Capture the warning code from the integration activity log.","Verify that new users are included in the configured sync group."]','Escalate when included users remain missing after a retry or warning codes persist.','2026-05-09','["integration","directory","sync","warning","employee","import"]'),
('KB-012','Safe Information Collection for Support Cases','General','Support should collect timestamps, visible error messages and non-sensitive identifiers without asking customers to share passwords or active tokens.','["Request timestamps with timezone.","Request visible error text and a request ID when available.","Never request passwords, recovery codes or token values."]','Use alongside the issue-specific article whenever engineering investigation requires diagnostics.','2026-02-12','["error","timestamp","diagnostic","request","support"]');
